kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  environment:
    KEY:
      from_secret: access_key
    TOKEN:
      from_secret: gcp_creds
      
  commands:
  - echo Initializing...
  - echo key $${KEY}
  - echo token $${TOKEN}
